export {default as Home } from '../Home';
export {default as About } from '../About';
export {default as Shop } from '../Shop';
export {default as Singleproduct } from '../Singleproduct';
export {default as Faq } from '../Faq';
export {default as Contact } from '../Contact';
export {default as Wishlist } from '../Wishlist';
export {default as Checkout } from '../Checkout';
export {default as Cart } from '../Cart';